### ISSUE TITLE
v2.0 roadmap

### ISSUE THREAD

**Issue by notpushkin** [notpushkin/twitaba#1]
- [ ] quotes
- [x] fetch more replies for threads
- [ ] implement some caching system
- [ ] display a proper error if the user has been rate-limited (happens a lot given the way we're abusing the APIs)
